// Persistent snapshot of each connector's most recent successful fetch, as RAW
// connector results (origin/mirror/native representations). When a connector
// fails, the loader falls back to this file so a single broken source doesn't
// blank out the dashboard. The builder reconciles + merges these at build time;
// the snapshot itself stays raw.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import type { ConnectorResult, ProjectSource } from '../types/project';

export type ConnectorKey = Exclude<ProjectSource, 'manual'>;

export type ConnectorSnapshot = {
  /** ISO timestamp of the most recent SUCCESSFUL fetch. Preserved across
   *  subsequent failed attempts so the dashboard keeps showing the last
   *  known-good data. */
  lastScrapedAt: string;
  /** Results from the most recent SUCCESSFUL fetch. Preserved when the
   *  next attempt fails so a transient block doesn't blank out the source. */
  results: ConnectorResult[];
  /** Observability for the MOST RECENT attempt (success or failure) —
   *  refreshed on every build. Separated from `lastScrapedAt`/`results`
   *  so it's unambiguous which fields describe the data being shown vs.
   *  the most recent run. */
  lastAttempt: {
    /** ISO timestamp — fresh on every build, including failed runs. */
    at: string;
    /** Outcome of this attempt:
     *  - `true`: all configured input returned data (or no input);
     *  - `'partial'`: some returned, some didn't — incomplete but usable;
     *  - `false`: nothing usable, snapshot keeps previous results. */
    ok: boolean | 'partial';
    /** When `ok` is `'partial'` or `false`: human-readable reason. */
    error?: string;
  };
};

export type SnapshotFile = {
  /** Snapshot schema version — bump on breaking changes. */
  version: 5;
  _generated: string;
  connectors: Partial<Record<ConnectorKey, ConnectorSnapshot>>;
};

// Resolved relative to cwd (project root under `npm run`), not the module URL —
// which moves into dist/ after Astro bundles.
const SNAPSHOT_PATH = resolve(process.cwd(), 'generated/snapshot.json');

const GENERATED_NOTE =
  'Auto-generated by the build. Raw per-connector results — do not hand-edit; regenerate via `npm run build`.';

function emptySnapshot(): SnapshotFile {
  return { version: 5, _generated: GENERATED_NOTE, connectors: {} };
}

/** Migrate a v4 entry: the `ok` field was boolean — same shape, just widen
 *  the type contract. Existing values pass through untouched. */
type V4Connector = {
  lastScrapedAt?: string;
  results?: ConnectorResult[];
  lastAttempt?: { at?: string; ok?: boolean; error?: string };
};
function migrateFromV4(raw: { connectors?: Record<string, V4Connector> }): SnapshotFile {
  const out = emptySnapshot();
  for (const [k, v] of Object.entries(raw.connectors ?? {})) {
    if (!v || typeof v.lastScrapedAt !== 'string' || !Array.isArray(v.results)) continue;
    out.connectors[k as ConnectorKey] = {
      lastScrapedAt: v.lastScrapedAt,
      results: v.results,
      lastAttempt: {
        at: v.lastAttempt?.at ?? v.lastScrapedAt,
        ok: v.lastAttempt?.ok ?? true,
        ...(v.lastAttempt?.error ? { error: v.lastAttempt.error } : {}),
      },
    };
  }
  return out;
}

/** Migrate a v2 entry: v2 had no observability — treat existing entries as
 *  successful (they could only get written by a successful fetch under v2
 *  semantics) and synthesize a matching `lastAttempt`. */
type V2Connector = { lastScrapedAt?: string; results?: ConnectorResult[] };
function migrateFromV2(raw: { connectors?: Record<string, V2Connector> }): SnapshotFile {
  const out = emptySnapshot();
  for (const [k, v] of Object.entries(raw.connectors ?? {})) {
    if (!v || typeof v.lastScrapedAt !== 'string' || !Array.isArray(v.results)) continue;
    out.connectors[k as ConnectorKey] = {
      lastScrapedAt: v.lastScrapedAt,
      results: v.results,
      lastAttempt: { at: v.lastScrapedAt, ok: true },
    };
  }
  return out;
}

/** Migrate a v3 entry: v3 had a flat shape (ok/attemptedAt/error at the root
 *  alongside lastScrapedAt/results). Lift those into the nested lastAttempt. */
type V3Connector = {
  lastScrapedAt?: string;
  results?: ConnectorResult[];
  ok?: boolean;
  attemptedAt?: string;
  error?: string;
};
function migrateFromV3(raw: { connectors?: Record<string, V3Connector> }): SnapshotFile {
  const out = emptySnapshot();
  for (const [k, v] of Object.entries(raw.connectors ?? {})) {
    if (!v || typeof v.lastScrapedAt !== 'string' || !Array.isArray(v.results)) continue;
    out.connectors[k as ConnectorKey] = {
      lastScrapedAt: v.lastScrapedAt,
      results: v.results,
      lastAttempt: {
        at: v.attemptedAt ?? v.lastScrapedAt,
        ok: v.ok ?? true,
        ...(v.error ? { error: v.error } : {}),
      },
    };
  }
  return out;
}

export function readSnapshot(): SnapshotFile {
  if (!existsSync(SNAPSHOT_PATH)) return emptySnapshot();
  try {
    const parsed = JSON.parse(readFileSync(SNAPSHOT_PATH, 'utf8')) as SnapshotFile & { version?: number };
    if (parsed.version === 5 && parsed.connectors) {
      parsed._generated = GENERATED_NOTE;
      return parsed;
    }
    if (parsed.version === 4 && parsed.connectors) {
      return migrateFromV4(parsed as unknown as { connectors: Record<string, V4Connector> });
    }
    if (parsed.version === 3 && parsed.connectors) {
      return migrateFromV3(parsed as unknown as { connectors: Record<string, V3Connector> });
    }
    if (parsed.version === 2 && parsed.connectors) {
      return migrateFromV2(parsed as unknown as { connectors: Record<string, V2Connector> });
    }
    return emptySnapshot();
  } catch (err) {
    console.warn('[snapshot] read failed, starting empty:', err);
    return emptySnapshot();
  }
}

export function writeSnapshot(snapshot: SnapshotFile): void {
  mkdirSync(dirname(SNAPSHOT_PATH), { recursive: true });
  snapshot._generated = GENERATED_NOTE;
  writeFileSync(SNAPSHOT_PATH, JSON.stringify(snapshot, null, 2) + '\n', 'utf8');
}
