// Persistent snapshot of each connector's most recent successful fetch, as RAW
// connector results (origin/mirror/native representations). When a connector
// fails, the loader falls back to this file so a single broken source doesn't
// blank out the dashboard. The builder reconciles + merges these at build time;
// the snapshot itself stays raw.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import type { ConnectorResult, ProjectSource } from '../types/project';

export type ConnectorKey = Exclude<ProjectSource, 'manual'>;

export type ConnectorSnapshot = {
  /** ISO timestamp of the most recent SUCCESSFUL fetch. Preserved across
   *  subsequent failed attempts so the dashboard keeps showing the last
   *  known-good data. */
  lastScrapedAt: string;
  /** Results from the most recent SUCCESSFUL fetch. Preserved when the
   *  next attempt fails so a transient block doesn't blank out the source. */
  results: ConnectorResult[];
  /** Outcome of the most recent ATTEMPT (success OR failure). */
  ok: boolean;
  /** ISO timestamp of the most recent attempt — fresh on every build,
   *  including failed runs. */
  attemptedAt: string;
  /** When `ok` is false: human-readable failure reason. */
  error?: string;
};

export type SnapshotFile = {
  /** Snapshot schema version — bump on breaking changes. */
  version: 3;
  _generated: string;
  connectors: Partial<Record<ConnectorKey, ConnectorSnapshot>>;
};

// Resolved relative to cwd (project root under `npm run`), not the module URL —
// which moves into dist/ after Astro bundles.
const SNAPSHOT_PATH = resolve(process.cwd(), 'generated/snapshot.json');

const GENERATED_NOTE =
  'Auto-generated by the build. Raw per-connector results — do not hand-edit; regenerate via `npm run build`.';

function emptySnapshot(): SnapshotFile {
  return { version: 3, _generated: GENERATED_NOTE, connectors: {} };
}

/** Migrate a v2 snapshot in-place: v2 has no per-connector ok/attemptedAt.
 *  Treat existing entries as successful (they could only get written by a
 *  successful fetch under v2 semantics). */
function migrateFromV2(raw: { connectors?: Record<string, { lastScrapedAt?: string; results?: ConnectorResult[] }> }): SnapshotFile {
  const out = emptySnapshot();
  for (const [k, v] of Object.entries(raw.connectors ?? {})) {
    if (!v || typeof v.lastScrapedAt !== 'string' || !Array.isArray(v.results)) continue;
    out.connectors[k as ConnectorKey] = {
      lastScrapedAt: v.lastScrapedAt,
      results: v.results,
      ok: true,
      attemptedAt: v.lastScrapedAt,
    };
  }
  return out;
}

export function readSnapshot(): SnapshotFile {
  if (!existsSync(SNAPSHOT_PATH)) return emptySnapshot();
  try {
    const parsed = JSON.parse(readFileSync(SNAPSHOT_PATH, 'utf8')) as SnapshotFile & { version?: number };
    if (parsed.version === 3 && parsed.connectors) {
      parsed._generated = GENERATED_NOTE;
      return parsed;
    }
    if (parsed.version === 2 && parsed.connectors) {
      return migrateFromV2(parsed as unknown as { connectors: Record<string, { lastScrapedAt?: string; results?: ConnectorResult[] }> });
    }
    return emptySnapshot();
  } catch (err) {
    console.warn('[snapshot] read failed, starting empty:', err);
    return emptySnapshot();
  }
}

export function writeSnapshot(snapshot: SnapshotFile): void {
  mkdirSync(dirname(SNAPSHOT_PATH), { recursive: true });
  snapshot._generated = GENERATED_NOTE;
  writeFileSync(SNAPSHOT_PATH, JSON.stringify(snapshot, null, 2) + '\n', 'utf8');
}
