// Persistent snapshot of the most recent successful scrape per connector.
// When a connector fails (network blip, API outage, scrape regression), the
// loader falls back to this file so a single broken source doesn't blank out
// the dashboard.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import type { Project, ProjectSource } from '../types/project';

export type ConnectorKey = Exclude<ProjectSource, 'manual'>;

/** Project shape inside the snapshot — without loader-derived overlay fields. */
export type SnapshotProject = Omit<Project, 'featured' | 'hasDetail'>;

export type ConnectorSnapshot = {
  /** ISO timestamp of the most recent successful fetch. */
  lastScrapedAt: string;
  projects: SnapshotProject[];
};

export type SnapshotFile = {
  /** Snapshot schema version — bump on breaking changes. */
  version: 1;
  _generated: string;
  connectors: Partial<Record<ConnectorKey, ConnectorSnapshot>>;
};

// Resolved relative to cwd (project root when invoked via `npm run`),
// not the module URL — which moves into dist/ after Astro bundles.
const SNAPSHOT_PATH = resolve(process.cwd(), 'generated/snapshot.json');

const GENERATED_NOTE =
  'Auto-generated by the build. Do not hand-edit — regenerate via `npm run build`.';

function emptySnapshot(): SnapshotFile {
  return { version: 1, _generated: GENERATED_NOTE, connectors: {} };
}

function stripOverlay(p: Project): SnapshotProject {
  const { featured: _f, hasDetail: _h, ...rest } = p;
  return rest;
}

export function readSnapshot(): SnapshotFile {
  if (!existsSync(SNAPSHOT_PATH)) return emptySnapshot();
  try {
    const raw = readFileSync(SNAPSHOT_PATH, 'utf8');
    const parsed = JSON.parse(raw) as SnapshotFile;
    if (parsed.version !== 1 || !parsed.connectors) return emptySnapshot();
    parsed._generated = GENERATED_NOTE;
    return parsed;
  } catch (err) {
    console.warn('[snapshot] read failed, starting empty:', err);
    return emptySnapshot();
  }
}

export function writeSnapshot(snapshot: SnapshotFile): void {
  mkdirSync(dirname(SNAPSHOT_PATH), { recursive: true });
  snapshot._generated = GENERATED_NOTE;
  writeFileSync(SNAPSHOT_PATH, JSON.stringify(snapshot, null, 2) + '\n', 'utf8');
}

/** Convert a Project (with overlay fields) into a SnapshotProject (without). */
export function toSnapshotProject(p: Project): SnapshotProject {
  return stripOverlay(p);
}

/** Hydrate a SnapshotProject back into a Project with default overlay values. */
export function fromSnapshotProject(p: SnapshotProject): Project {
  return { ...p, featured: false, hasDetail: false };
}
