#!/usr/bin/env node
// Env-driven counterpart to scripts/init.mjs — generates
// projects.config.local.ts from form inputs the Setup workflow collects
// via workflow_dispatch. Run by .github/workflows/setup.yml on the CI
// runner so a forker never needs a local clone.
//
// Required env vars:
//   GH_OWNER   - the github username (workflow injects from github.repository_owner)
//   GH_REPO    - the repo name      (workflow injects from github.event.repository.name)
//
// Optional env vars (all map 1:1 to projects.config knobs):
//   SITE_TITLE, SITE_TAGLINE, SITE_ABOUT,
//   NPM_USER, DOCKER_USER, STACKOVERFLOW_USER_ID,
//   CHROME_EXTENSION_IDS  (comma-separated 32-char ids)
//   GPLAY_PACKAGES        (comma-separated package names)
//   GNOME_EXTENSION_IDS   (comma-separated numeric ids)
//   DEFAULT_LANGUAGE      ('en' / 'he' / '' for "All")
//   FAVICON_SHAPE         ('rounded' / 'square' / 'auto')

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

function need(name) {
  const v = process.env[name];
  if (!v) {
    console.error(`Missing required env var: ${name}`);
    process.exit(2);
  }
  return v;
}

function opt(name, fallback = '') {
  const v = process.env[name];
  return v === undefined || v === '' ? fallback : v;
}

/** Split a comma-or-whitespace list of items, trim each, drop empties. */
function parseList(raw) {
  if (!raw) return [];
  return raw
    .split(/[\s,]+/g)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

const owner = need('GH_OWNER');
const repo = need('GH_REPO');
const site = `https://${owner}.github.io`;
const base = `/${repo}`;

const siteTitle = opt('SITE_TITLE', 'My Projects');
const siteTagline = opt('SITE_TAGLINE', '');
const siteAbout = opt('SITE_ABOUT', '');
const npmUser = opt('NPM_USER', '');
const dockerUser = opt('DOCKER_USER', '');
const soUserId = opt('STACKOVERFLOW_USER_ID', '');
const chromeIds = parseList(opt('CHROME_EXTENSION_IDS'));
const gplayPkgs = parseList(opt('GPLAY_PACKAGES'));
const gnomeIds = parseList(opt('GNOME_EXTENSION_IDS')).map((s) => Number(s)).filter(Number.isFinite);
const defaultLang = opt('DEFAULT_LANGUAGE', '');
const faviconShape = opt('FAVICON_SHAPE', '');

function tsString(s) {
  // Single quote, with `'` escaped — keeps the generated file readable.
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

const parts = [];

parts.push(`import baseConfig from './projects.config';`);
parts.push('');
parts.push(`// Generated by .github/workflows/setup.yml — re-run that workflow to`);
parts.push(`// regenerate with new values. Edits made here will be overwritten on`);
parts.push(`// the next Setup run.`);
parts.push(`export default {`);
parts.push(`  ...baseConfig,`);
parts.push(`  deployment: {`);
parts.push(`    ...baseConfig.deployment,`);
parts.push(`    site: ${tsString(site)},`);
parts.push(`    base: ${tsString(base)},`);
parts.push(`  },`);

// meta block — only emit overrides for fields the form set.
const metaOverrides = [];
if (siteTitle) metaOverrides.push(`    siteTitle: ${tsString(siteTitle)},`);
if (siteTagline) metaOverrides.push(`    siteTagline: ${tsString(siteTagline)},`);
if (siteAbout) metaOverrides.push(`    siteAbout: ${tsString(siteAbout)},`);
if (defaultLang) metaOverrides.push(`    defaultLanguage: ${tsString(defaultLang)},`);
if (faviconShape) metaOverrides.push(`    faviconShape: ${tsString(faviconShape)},`);
if (metaOverrides.length > 0) {
  parts.push(`  meta: {`);
  parts.push(`    ...baseConfig.meta,`);
  parts.push(...metaOverrides);
  parts.push(`  },`);
}

// user block — always emit (github is always set; the others are optional)
parts.push(`  user: {`);
parts.push(`    ...baseConfig.user,`);
parts.push(`    github: ${tsString(owner)},`);
if (npmUser) parts.push(`    npm: ${tsString(npmUser)},`);
if (dockerUser) parts.push(`    docker: ${tsString(dockerUser)},`);
parts.push(`  },`);

// sources block — only when at least one source has values
if (chromeIds.length > 0 || gplayPkgs.length > 0 || gnomeIds.length > 0 || soUserId) {
  parts.push(`  sources: {`);
  parts.push(`    ...baseConfig.sources,`);
  if (chromeIds.length > 0) {
    parts.push(`    chrome: {`);
    parts.push(`      ...baseConfig.sources.chrome,`);
    parts.push(`      extensionIds: [`);
    for (const id of chromeIds) parts.push(`        ${tsString(id)},`);
    parts.push(`      ],`);
    parts.push(`    },`);
  }
  if (gplayPkgs.length > 0) {
    parts.push(`    gplay: {`);
    parts.push(`      ...baseConfig.sources.gplay,`);
    parts.push(`      packages: [`);
    for (const pkg of gplayPkgs) parts.push(`        ${tsString(pkg)},`);
    parts.push(`      ],`);
    parts.push(`    },`);
  }
  if (gnomeIds.length > 0) {
    parts.push(`    gnome: {`);
    parts.push(`      ...baseConfig.sources.gnome,`);
    parts.push(`      extensionIds: [${gnomeIds.join(', ')}],`);
    parts.push(`    },`);
  }
  if (soUserId) {
    parts.push(`    stackoverflow: {`);
    parts.push(`      ...baseConfig.sources.stackoverflow,`);
    parts.push(`      userId: ${tsString(soUserId)},`);
    parts.push(`    },`);
  }
  parts.push(`  },`);
}

parts.push(`  featured: [`);
parts.push(`    // 'slug-to-pin-at-the-top',`);
parts.push(`  ],`);
parts.push(`  manual: [`);
parts.push(`    // closed-source / retired / Wayback-archived projects`);
parts.push(`  ],`);
parts.push(`};`);
parts.push('');

const content = parts.join('\n');
const target = resolve(process.cwd(), 'projects.config.local.ts');
writeFileSync(target, content);
console.log(`Wrote ${target}`);
console.log(`  deployment.site: ${site}`);
console.log(`  deployment.base: ${base}`);
console.log(`  user.github:     ${owner}`);
if (npmUser) console.log(`  user.npm:        ${npmUser}`);
if (dockerUser) console.log(`  user.docker:     ${dockerUser}`);
if (chromeIds.length) console.log(`  chrome ids:      ${chromeIds.length}`);
if (gplayPkgs.length) console.log(`  gplay packages:  ${gplayPkgs.length}`);
if (gnomeIds.length) console.log(`  gnome ids:       ${gnomeIds.length}`);
if (soUserId) console.log(`  stackoverflow:   ${soUserId}`);
